### ISSUE TITLE
Not very clean error handling when entering an empty password

### ISSUE THREAD

**Issue by kkwoker** [colstrom/git-ready#3]
```
[Warning] Unable to find a configuration in ["/etc", "/usr/local/etc", "~/.config", "."]
[Info] Entering Interactive Setup (^c to exit)
Enter the path to your workspace.
/Users/kinnankwok/Documents/Sandbox/git-ready-workspace
[Info] If you leave this blank, git-ready will do most of the work for you. As a fallback, you can generate your own at https://github.com/settings/tokens/new
Enter your GitHub Personal Access Token:

Enter your GitHub login:
kkwoker
Enter your GitHub password:

[Failure] Invalid Credentials
/Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.2/lib/git-ready/interactive_setup.rb:53:in `setup': undefined method `[]' for nil:NilClass (NoMethodError)
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.2/lib/git-ready/interactive_setup.rb:15:in `start'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.2/lib/git-ready/settings.rb:21:in `rescue in <class:Settings>'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.2/lib/git-ready/settings.rb:9:in `<class:Settings>'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.2/lib/git-ready/settings.rb:8:in `<top (required)>'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.2/lib/git-ready.rb:1:in `require_relative'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.2/lib/git-ready.rb:1:in `<top (required)>'
  from /Users/kinnankwok/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/kinnankwok/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.2/bin/git-ready:3:in `<top (required)>'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/git-ready:23:in `load'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/git-ready:23:in `<main>'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by colstrom** [comment]
Thanks! Fixed in 30b211cee6693ff0ea89bd712eb24f745a63b7bc, included in `0.8.4`
