### ISSUE TITLE
Unsupported URL protocol when cloning repos

### ISSUE THREAD

**Issue by kkwoker** [colstrom/git-ready#5]
```
[Info] Forking all telusdigital repositories to kkwoker
[#######################################################################################] [60/60] [100.00%] [00:40] [00:00] [ 1.48/s][Info] Cloning all forked repositories into /Users/kinnankwok/Documents/Sandbox/git-ready-workspace
/Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.3/lib/git-ready/workspace.rb:24:in `clone_at': Unsupported URL protocol (Rugged::NetworkError)
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.3/lib/git-ready/workspace.rb:24:in `clone'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.3/lib/git-ready/workspace.rb:33:in `block in setup'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.3/lib/git-ready/workspace.rb:30:in `each'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.3/lib/git-ready/workspace.rb:30:in `setup'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.3/bin/git-ready:19:in `<top (required)>'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/git-ready:23:in `load'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/git-ready:23:in `<main>'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kkwoker** [comment]
Problem still persists in version 0.8.4

```
  [Info] Forking all telusdigital repositories to kkwoker
  [###############################################################################################################################################################################################################################] [60/60] [100.00%] [00:33] [00:00] [ 1.79/s][Info] Cloning all forked repositories into /Users/kinnankwok/Documents/Sandbox/git-ready-workspace
  /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.4/lib/git-ready/workspace.rb:24:in `clone_at': Unsupported URL protocol (Rugged::NetworkError)
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.4/lib/git-ready/workspace.rb:24:in `clone'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.4/lib/git-ready/workspace.rb:33:in `block in setup'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.4/lib/git-ready/workspace.rb:30:in `each'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.4/lib/git-ready/workspace.rb:30:in `setup'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.4/bin/git-ready:19:in `<top (required)>'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/git-ready:23:in `load'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/git-ready:23:in `<main>'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by colstrom** [comment]
Changes in 81759c24d3662fd1d28e4504b7ee5b83dea4e570 should provide some clarity around this one. If you update to `0.8.5`, what output do you get?

**Comment by kkwoker** [comment]
```
[Info] Cloning all forked repositories into /Users/kinnankwok/Documents/Sandbox/git-ready-workspace
[Failure] Failed to clone repository git@github.com:kkwoker/forge.git to path /Users/kinnankwok/Documents/Sandbox/git-ready-workspace/forge
/Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/lib/git-ready/workspace.rb:16:in `new': Failed to resolve path '/Users/kinnankwok/Documents/Sandbox/git-ready-workspace/forge': No such file or directory (Rugged::OSError)
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/lib/git-ready/workspace.rb:16:in `configure_remotes'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/lib/git-ready/workspace.rb:35:in `block in setup'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/lib/git-ready/workspace.rb:32:in `each'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/lib/git-ready/workspace.rb:32:in `setup'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/bin/git-ready:19:in `<top (required)>'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/git-ready:23:in `load'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/git-ready:23:in `<main>'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kkwoker** [comment]
Creating the directory gives me:

```
[Info] Forking all telusdigital repositories to kkwoker
[##############################################################################################################################################################] [60/60] [100.00%] [00:28] [00:00] [ 2.08/s][Info] Cloning all forked repositories into /Users/kinnankwok/Documents/Sandbox/git-ready-workspace
[Failure] Failed to clone repository git@github.com:kkwoker/forge.git to path /Users/kinnankwok/Documents/Sandbox/git-ready-workspace/forge
/Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/lib/git-ready/workspace.rb:16:in `new': Could not find repository from '/Users/kinnankwok/Documents/Sandbox/git-ready-workspace/forge' (Rugged::RepositoryError)
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/lib/git-ready/workspace.rb:16:in `configure_remotes'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/lib/git-ready/workspace.rb:35:in `block in setup'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/lib/git-ready/workspace.rb:32:in `each'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/lib/git-ready/workspace.rb:32:in `setup'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/gems/git-ready-0.8.6/bin/git-ready:19:in `<top (required)>'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/git-ready:23:in `load'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/git-ready:23:in `<main>'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
  from /Users/kinnankwok/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```
